### ISSUE TITLE
bazhara

### ISSUE THREAD

**Issue by levviofan100** [Dracopa/Bazharanalfuck#1]
can u add please released?

**Comment by NathanPrivate** [comment]
English?

**Comment by Paster1337** [comment]
this is not bazhar? no mastermind had the jaxx cheat while back

**Comment by Dracopa** [comment]
> can u add please released?

You want a dll binary?

**Comment by Dracopa** [comment]
> this is not bazhar? no mastermind had the jaxx cheat while back

Nice to see you here bazhar 👍

**Comment by NeoxPublic** [comment]
He has a point jaxx did have the cheat along time ago unless bazhar bought source
